version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    reviewers:
      - 'Timo'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    groups:
      angular:
        patterns:
          - '@angular/*'
      development:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(ci)'
